### ISSUE TITLE
Use associate array for the dependencies' properties

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/webthree-umbrella-cross#12]

**Comment by bobsummerwill** [comment]
Please could you explain this one more, @anthony-cros?   Thanks!

**Comment by anthony-cros** [comment]
so we'd switch to using [bash associate array](http://www.linuxjournal.com/content/bash-associative-arrays) (think map in java, dictionary in python and so on)

Looking at [cmake](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/setup.sh#L54) for instance, it has a lot of properties such as its [version](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/setup.sh#L74), [archive name](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/setup.sh#L86), [download url](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/setup.sh#L95), ... that should all be "encapsulated" under the same concept. now bash doesn't really have objects, so an associative array is a good compromise.

this would allow us to generalize a number of places in the scripts. for instance [this](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/setup.sh#L54) would become something like `/usr/bin/cmake ${COMPONENT["basedir"]}` rather (i've had plenty of errors due to incorrectly hard-coded components name like "CMAKE_BASE_DIR").Alternatively we could do it as `${BASE_DIR[$COMPONENT]}` rather, depends which categorisation makes the most sense

**Comment by bobsummerwill** [comment]
Right.   Gotcha.   Low priority.

**Comment by anthony-cros** [comment]
oops :)

just meant to comment: yes, low priority, just something to keep in mind in particular if you find yourself adding more components
