### ISSUE TITLE
eth scripts: address MHD warnings if possible

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/webthree-umbrella-cross#14]

**Comment by bobsummerwill** [comment]
Could you do a gist of them, please?   Thanks!

**Comment by anthony-cros** [comment]
either they have been addressed "indirectly", so it wasn't MHD that was throwing warnings, the latest build seems fine.

I'll close unless we encounter warnings again!

**Comment by bobsummerwill** [comment]
Is there some trivial way to enable warnings-as-errors for this, to lock-in the goodness?

**Comment by anthony-cros** [comment]
i think there's a make flag for it, we could hack the Makefile produced by autoconf for that

**Comment by bobsummerwill** [comment]
Yeah ... never mind.   Low priority.
Maybe I'll do a global "warnings-as-errors" for everything at some point?
But we have bigger fish to fry, eh?
