### ISSUE TITLE
finish dot file

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/webthree-umbrella-cross#16]

**Comment by bobsummerwill** [comment]
Yes please.   This is something very important to capture NOW while the information is fresh in your mind.

**Comment by anthony-cros** [comment]
sounds good, i understand better how some of them fit with each other now (libscrypt, secp256k1, ...)

**Comment by bobsummerwill** [comment]
Please can you do this ASAP?
That is the one thing which I think we can get backported right now :-)

**Comment by anthony-cros** [comment]
sounds good, I'll take care of that first

**Comment by bobsummerwill** [comment]
Thanks!

**Comment by bobsummerwill** [comment]
Would be awesome to get something, ANYTHING, upstreamed, eh :-)

**Comment by anthony-cros** [comment]
ha ha, yes, and that's our best shot so far!!

**Comment by bobsummerwill** [comment]
Indeed it is :-)   Let us make it so!

**Comment by bobsummerwill** [comment]
Updated output -> https://ipfs.pics/ipfs/QmU5DL8HnBvn3FpHBCFX69suLpSh2qCBZKg1FzmUfBiDX5

**Comment by bobsummerwill** [comment]
Created a new PR on waiting for the merge, and assigned it to me:
    https://github.com/doublethinkco/webthree-umbrella-cross/issues/34

Thanks!   We can call this closed.
