### ISSUE TITLE
Use git sub-modules for external dependencies as much as possible

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/webthree-umbrella-cross#17]

**Comment by bobsummerwill** [comment]
Are you talking about the proposal to use git sub-modules for external dependencies too?   Rather than WGETs of random ZIPs?   @anthony-cros

**Comment by anthony-cros** [comment]
yes, exactly, to avoid (hopefully) the kind of issues we've had with MPFR and CRYPTOPP binaries! hopefully they all use a github or similar

**Comment by bobsummerwill** [comment]
Right, so in "best" to "OK" order, we would ...

1. Just use sub-module for the release branch in an existing github repo which is exactly the same as the ZIPs, if such exists.
2. Or some of them have mirrors which somebody has made other than the team themselves.   If those have the same content then we would go with that instead.    We're not guaranteed them will be maintained to the same degree, and they may become a burden in the future, but it saves us some work for now.
3. Worst-case we just un-ZIP the versions we need into our own doublethinkco/<repo> and reference those as sub-modules.

**Comment by anthony-cros** [comment]
yes, though from what i've seen most seemed to meet (1)! cryptopp might not, but it won't be around much much longer i think

**Comment by bobsummerwill** [comment]
See #46 and #47.

**Comment by bobsummerwill** [comment]
Covered just fine with #46 and #47.   Deleting this which is now just a dupe.
