### ISSUE TITLE
Work with geth team to address silent failure

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/webthree-umbrella-cross#25]

**Comment by anthony-cros** [comment]
Issue may have been resolved, see https://github.com/ethereum/go-ethereum/issues/1962#issuecomment-158896529 (to be confirmed)

**Comment by bobsummerwill** [comment]
Yep - let's close this when we've gone end-to-end on:

https://github.com/doublethinkco/webthree-umbrella-cross/issues/29

... with the go 1.5-develop branch, and done a full sync on the main network on your TM1!

**Comment by bobsummerwill** [comment]
@anthony-cros Please could you try this on the TM1 over the weekend?   I cannot close this one off myself.

Just making a cross-built geth with go-1.5-develop and seeing if it can sync all of the main net without falling over!

**Comment by bobsummerwill** [comment]
But we'll move the tracking of the work to ... https://github.com/doublethinkco/go-ethereum-cross/issues/1.
