### ISSUE TITLE
Test if the buildbot geth binary works on iOS

### ISSUE THREAD

**Issue by bobsummerwill** [doublethinkco/webthree-umbrella-cross#27]

**Comment by anthony-cros** [comment]
Hey Bob, I don't own any iOS devices :-S

**Comment by bobsummerwill** [comment]
OK - np.   I'll do this one, in that case!

**Comment by bobsummerwill** [comment]
Superceded by https://github.com/doublethinkco/go-ethereum-cross/issues/6
