### ISSUE TITLE
Document how to attach GDB

### ISSUE THREAD

**Issue by bobsummerwill** [doublethinkco/webthree-umbrella-cross#28]
Hey @anthony-cros!    So I have managed to cross-build myself an eth.tgz on Azure with a Docker container running on Core OS, then docker cp back to Core OS and then scp back to my Mac.

Then sdb push to the Gear S2 and then I will be running it imminently.

But what are the extra steps you needed to follow to attach GDB?    Also, are our build scripts just doing -g in a hardcoded way to add symbols?

**Comment by bobsummerwill** [comment]
I'm actually doing the push in Eclipse, not with sdb.   Super-slow and file-transfer seem more reliable in the IDE.

**Comment by bobsummerwill** [comment]
What was your on-device command for the tgz unpacking?
We should actually do some little shell-script and add it into the TGZ within our cross-build process.   tizen-run.sh or whatever.

**Comment by bobsummerwill** [comment]
Just tar xvfz, I guess.

**Comment by anthony-cros** [comment]
yes, exactly (tar zxf, v is just for verbose)

regarding gdb, it is [this flag](https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/webthree.sh#L45) that adds the "-g" option, though we should probably make that configurable

**Comment by bobsummerwill** [comment]
Are you just doing something like this?

http://developerblog.redhat.com/2015/04/28/remote-debugging-with-gdb/

**Comment by anthony-cros** [comment]
I see, the link I have provided above has slightly changed since, that'll teach me to point to "develop"... here's a better [link](https://github.com/doublethinkco/webthree-umbrella/blob/41879a0/cross-build/ethereum/webthree.sh#L55)

**Comment by anthony-cros** [comment]
so no, i'm not actually doing it "remotely", just dropping in the tizen shell

**Comment by bobsummerwill** [comment]
Aha - so gdb is INSTALLED on the TM1?
No such luxury for me on the Gear S2, hence my question.
I assumed that you were in the same situation as me, but you are NOT!
Hence talking at cross-purposes a bit.

**Comment by anthony-cros** [comment]
yes :), have you checked in all the *bin dir (the usual suspects like /sbin and so on, sometimes they're just not on the path)

**Comment by bobsummerwill** [comment]
I will look around, but I suspect it is NOT installed intentionally, because Gear S2 is a retail device, not a developer phone like the TM1.

**Comment by bobsummerwill** [comment]
I have asked on the Tizen IRC channel.

**Comment by bobsummerwill** [comment]
I've asked Raster too.
No gdb files on the Gear S2.   Looked everywhere.   Probably as per plan.

Maybe I can get the appropriate files transferred from your TM1 onto the Gear S2?   Can you see where they are, and which ones might be needed?    If you make me a ZIP of likely candidates, I can try :-)

**Comment by anthony-cros** [comment]
I'm not sure, if that helps this is what `file` says about it:

```
$ file /usr/bin/gdb
/usr/bin/gdb: ELF 32-bit LSB executable, ARM, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, stripped
```

**Comment by bobsummerwill** [comment]
OK - let's try anyway!
Thanks for the gdb.   Ran that.

Step #2 is ...

./gdb: /lib/libc.so.6: version `GLIBC_2.15' not found (required by ./gdb)

Let's just feed it what it wants, one-by-one until we hit a roadblock!

**Comment by anthony-cros** [comment]
i'll send you the whole content of /lib :D

**Comment by bobsummerwill** [comment]
Yep - thanks!

**Comment by bobsummerwill** [comment]
OK - this is never going to work.

See http://stackoverflow.com/questions/23958366/fixing-libc-so-6-unexpected-reloc-type-0x25
See http://stackoverflow.com/questions/847179/multiple-glibc-libraries-on-a-single-host/851229#851229

Let's abort mission for now.
