### ISSUE TITLE
The sub-modules in our webthree-umbrella fork are incorrect

### ISSUE THREAD

**Issue by bobsummerwill** [doublethinkco/webthree-umbrella-cross#30]
You can see this if you try to create a pull-request back to origin.

I think I screwed them up, so they are just a little wrong.

Please could you just fix them up?  Without that we'll be building the wrong thing at the moment.  Thanks!

We should ONLY have the cross-build diffs and the dot diagram.

**Comment by bobsummerwill** [comment]
I would do this myself, but am tied up right now.
If I get a chance then I will grab this back and do it myself.
That might turn out to make sense anyway, if you are focussing on geth right now.

**Comment by anthony-cros** [comment]
sounds good, i'll try to look into that while geth syncs the blockchain!

**Comment by bobsummerwill** [comment]
Thanks!   Yes, you will have some spare time.
I think there is some git-foo I am missing with regard to understanding how best to maintain sub-modules between forks and origin repos.
Right now we should be identical, so we can test if Gav's edits as-is get us past the statics.
If they don't then we would flip back to our webthree-umbrella fork, and re-add my edits which I backed out.

**Comment by bobsummerwill** [comment]
OK - got all that fixed up.

The other sub-modules just involved cd-ing into the sub-dirs, then git checkout develop, git pull.

And libweb3core was this ..

http://stackoverflow.com/questions/2155887/git-submodule-head-reference-is-not-a-tree-error

I will re-run my Docker container and see if I can get a new binary.     I was having no luck sdb push-ing my last one to the Gear S2 (maybe timeouts?), but perhaps if I make a new one you will have more luck on the TM1.
