### ISSUE TITLE
Can we NOT build CMake?

### ISSUE THREAD

**Issue by bobsummerwill** [doublethinkco/webthree-umbrella-cross#33]
It takes so damn long.

I wish we didn't build CMake, @anthony-cros.   This was because it needed to be a newer version, right?

I get a feeling that there is an extra PPA we can use here instead.  I might look at that.

**Comment by bobsummerwill** [comment]
See http://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu-14-04

**Comment by anthony-cros** [comment]
this for sure would save time!

**Comment by bobsummerwill** [comment]
Fixed as of:

https://github.com/doublethinkco/webthree-umbrella-cross/commit/df2265c4e1832e9889662ac7f6576fef4e2258a6

https://github.com/doublethinkco/webthree-umbrella/commit/813b05c90df8159a55101f2b07f71dfccea83bc7
