### ISSUE TITLE
Create final PR for DOT graph generation, and CMake tweaks

### ISSUE THREAD

**Issue by bobsummerwill** [doublethinkco/webthree-umbrella-cross#34]
See https://github.com/ethereum/webthree-umbrella/pull/90

**Comment by anthony-cros** [comment]
renamed the PR :)

**Comment by bobsummerwill** [comment]
Thanks!

**Comment by bobsummerwill** [comment]
Moved to https://github.com/ethereum/webthree-umbrella/pull/91.

I will do a fresh pass on the edges too, based on a tip from Gav.

**Comment by bobsummerwill** [comment]
Merged :-)

https://github.com/ethereum/webthree-umbrella/pull/94

**Comment by anthony-cros** [comment]
yay! :D

**Comment by bobsummerwill** [comment]
Ding dong!
