### ISSUE TITLE
Remove timestamp element from paths

### ISSUE THREAD

**Issue by bobsummerwill** [doublethinkco/webthree-umbrella-cross#39]
This kills incremental builds and testing and should be part of deployment process, not build process.   Especially with the Docker context, the containers provide that isolation anyway.   We don't need that on the file system within the container too

**Comment by bobsummerwill** [comment]
DONE - CC @anthony-cros

**Comment by anthony-cros** [comment]
sounds good, I was thinking of simply making a softlink such that ~/eth/latest -> ~/eth/151130092319 (if 151130092319 was the latest)

> This kills incremental builds

the scripts allowed specifying the timestamp to reuse for that purpose though

**Comment by bobsummerwill** [comment]
Right - but I don't think there is any need for this pattern within the build process itself.    Parallel builds can be achieved by cloning into different source directories in the first place if you want complete "parallel tree" workflow.

Within Docker, none of this is a problem at all, and I think that it is better to handle it outside of the build process for the repo if you need to have multiple instances.

Is the issue just that we are generating intermediate and working directories and outputs to a fixed global location?   I think it is, right?

Like this uniqifying is something which needs to be in a wrapper AROUND these scripts, not within them.

I'll keep iterating on this stuff.    Sorry if I stamp on your toes a bit ... :-)

**Comment by anthony-cros** [comment]
> I'll keep iterating on this stuff. Sorry if I stamp on your toes a bit ... :-)

no worries, i would have eventually gotten rid of it as the scripts matured anyway!
