### ISSUE TITLE
Support C.H.I.P.

### ISSUE THREAD

**Issue by bobsummerwill** [doublethinkco/webthree-umbrella-cross#40]
As of November 29th we have a runtime error as per @phonikg.

**Comment by bobsummerwill** [comment]
C.H.I.P. install went well, but then:

chip@chip:~/eth/bin$ ./eth
(++)Ethereum
Beware. You're entering the Frontier!
⧎ ℹ  05:06:36|eth  Id: ##7346fb5b…
pure virtual method called
terminate called without an active exception
Aborted
chip@chip:~/eth/bin$ 


So close...

**Comment by bobsummerwill** [comment]
See #10, but we'll move C.H.I.P. specific discussion here

**Comment by bobsummerwill** [comment]
Aside.   Have you ever tried a native eth build on C.H.I.P.  @phonikg?   I think the answer is 'not yet'.

Is that the case?

**Comment by phonikg** [comment]
So I have never used gdb before.  It was not pre-installed with the Debian img supplied by NTC.  I installed via: `sudo apt-get install gdb`

it now runs, but can you confirm that the exact syntax to utilize it is in fact: `gdb ./eth` ? This what I currently get which leads me to believe either I'm not issuing the command properly, or there are additional commands to issue once inside the `(gdb)` :+1: 

chip@chip:~/eth/bin$ gdb ./eth
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./eth...done.
(gdb)

**Comment by phonikg** [comment]
@bobsummerwill Correct: not yet.

**Comment by bobsummerwill** [comment]
I've not used it myself command-line for a long time either.   Looks like you just need to do 'run'.

http://www.chemie.fu-berlin.de/chemnet/use/info/gdb/gdb_5.html

You are in the GDB shell, but I imagine you can do gdb --run ./eth or similar on the command line to do it non-interactively.

**Comment by bobsummerwill** [comment]
Gdb is just the GNU debugger.   Nearly everwhere it is used is wrapped in layers of graphical debuggers now, or remote debugging where you have a gdbserver process on device talking the 'augmented' application and another GDB process on your host machine talking to gdbserver on the target.

**Comment by phonikg** [comment]
Okay, this is what it returned:

(gdb) run
Starting program: /home/chip/eth/bin/eth 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
(++)Ethereum
Beware. You're entering the Frontier!
⧎ ℹ  16:54:20|eth  Id: ##c72bb614…
[New Thread 0xb474f450 (LWP 1336)]
[New Thread 0xb3dff450 (LWP 1337)]
pure virtual method called
terminate called without an active exception

Program received signal SIGABRT, Aborted.
[Switching to Thread 0xb3dff450 (LWP 1337)]
__libc_do_syscall ()
    at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
44	../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
(gdb)

**Comment by phonikg** [comment]
What is best route at this point?  Would it be greatly helpful to try to compile on device first?

**Comment by bobsummerwill** [comment]
I think @anthony-cros hit something very similar looking at some point.

Yeah - I think it would certainly help to try a native build on device.   It might 'just work' and would be the best long-term solution for C.H.I.P. anyway.

Cross-builds for SBC are nice-to-have for various reasons but are not essential.   Namely ...

1. You can do a build without needing the device
2. The build process will likely be much faster, because you can use a kick-ass desktop or server.
3. Err ....

Or you HAVE to cross-build, due to platform limitations (iOS, Android, Tizen, PlayStation, XBOX, many embedded platforms).

**Comment by phonikg** [comment]
This is fairly low priority I imagine, but would have been nice if it *just worked*

Hmmm... C.H.I.P. is also very light... only 3GB left on the EMMC.  Might be tight to build "on device", however there is no room (or storage expansion) for the blockchain anyway.

**Comment by phonikg** [comment]
Also, I understand what you are saying regarding cross-builds not being **necessary** for most devices, but I tell you it is nice to finally have a 5 minute ethereum install for the SBC's!!!

^^^understatement of the month^^^

**Comment by bobsummerwill** [comment]
What was your previous setup process versus what you are doing now?

Were you always building natively per device?   You could likely have built natively once, copied the files off to your desktop and reused them on the other devices.    Though I guess that might not have worked depending on the ABI settings for each ... ?

Well anyway - if if has helped your workflow then that's good!

**Comment by anthony-cros** [comment]
> I think @anthony-cros hit something very similar looking at some point.

no I think it's a new message actually, though it does resemble the ones we typically get

> (gdb) run

@phonikg , could you also issue `bt` (for backtrace) at the prompt and after `run` finishes?

**Comment by phonikg** [comment]
Yes @anthony-cros I will try soon.

**Comment by bobsummerwill** [comment]
Hey @phonikg!   Please could you try https://github.com/doublethinkco/webthree-umbrella-cross/releases/tag/crosseth-armhf-15-12-17 on your C.H.I.P?   You are still the only "blessed individual" with one :-)

**Comment by phonikg** [comment]
UPDATE!

root@chip:~/eth/bin# ./eth
./eth: error while loading shared libraries: libboost_thread.so.1.59.0: cannot open shared object file: No such file or directory

**Comment by phonikg** [comment]
Me thinks this is a $PATH issue...

**Comment by phonikg** [comment]
Et Voila:

![image](https://cloud.githubusercontent.com/assets/7241066/12935594/eff8390e-cf64-11e5-866a-2f4e5a712f6d.png)

**Comment by anthony-cros** [comment]
nice!!

**Comment by bobsummerwill** [comment]
Oh my goodness!   Thanks, @phonikg.

Another cell bites the dust.    Tweet it up, and I'll link to the tweet in the umbrella-cross README matrix.

Best wishes!

**Comment by bobsummerwill** [comment]
I see you already tweeted.   All done-and-dusted.   Many thanks :-)
https://twitter.com/EthEmbedded/status/697220510208258048
