### ISSUE TITLE
Support official GCC cross-compiler binaries

### ISSUE THREAD

**Issue by bobsummerwill** [doublethinkco/webthree-umbrella-cross#42]
https://github.com/doublethinkco/webthree-umbrella-cross/issues/10

@anthony-cros said -  no i meant the apt-get install g++-arm-linux-gnueabi/apt-get install g++-arm-linux-gnueabihf combination, sadly I already tried the armhf binary i created earlier, but no dice

Right.  Sure - give it a whirl if you get a chance.   From what I could see when I had a quick look at the environment variables, etc, it should be a matter of just changing the environment variables to point to the new globally-installed GCC binaries instead of the ones we made.   And there is at least one hack which requires the addition of the directory containing those to the path.   I think they are now ALREADY on the path, so maybe just unqualified executable names are all we need now?

**Comment by anthony-cros** [comment]
> a matter of just changing the environment variables to point to the new globally-installed GCC binaries instead of the ones we made.

yes, I think that might just do the trick, i'll give it a shot!

**Comment by anthony-cros** [comment]
first binary build with the armhf version:

```
$ readelf -A /home/xcompiler/eth/installs/curl/bin/curl
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3-D16
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: SP and DP
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
```

next up is eth...

**Comment by bobsummerwill** [comment]
So that is with you NOT using our xcompiler binaries, but using those installed ones instead?  Cool.    Were the edits pretty minimal?

**Comment by anthony-cros** [comment]
> Were the edits pretty minimal?

yes and no, I really just hacked around that one curl script, I think edits for the whole set of scripts will be a bit more work

**Comment by anthony-cros** [comment]
starting work on this, i.e. making this an option for the entier run as opposed to just a hack

**Comment by anthony-cros** [comment]
WIP branch: https://github.com/doublethinkco/webthree-umbrella-cross/tree/using-built-in-compilers

With this, I'm able to build most of the components but get an error with _libjson_rpc_cpp_:
```
	cd /home/xcompiler/eth/wd/libjson-rpc-cpp/src/jsonrpccpp && /usr/bin/cmake -E cmake_link_script CMakeFiles/jsonrpccommon.dir/link.txt --verbose=1
	/usr/bin/arm-linux-gnueabihf-g++  -fPIC   -shared -Wl,-soname,libjsonrpccpp-common.so.0 -o ../../lib/libjsonrpccpp-common.so.0.6.0 CMakeFiles/jsonrpccommon.dir/common/errors.cpp.o CMakeFiles/jsonrpccommon.dir/common/specificationwriter.cpp.o CMakeFiles/jsonrpccommon.dir/common/procedure.cpp.o CMakeFiles/jsonrpccommon.dir/common/exception.cpp.o CMakeFiles/jsonrpccommon.dir/common/specificationparser.cpp.o /home/xcompiler/eth/installs/jsoncpp/lib/libjsoncpp.a 
	/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld: /home/xcompiler/eth/installs/jsoncpp/lib/libjsoncpp.a(json_reader.cpp.o): relocation R_ARM_THM_MOVW_ABS_NC against `_ZNSs4_Rep20_S_empty_rep_storageE' can not be used when making a shared object; recompile with -fPIC
	/home/xcompiler/eth/installs/jsoncpp/lib/libjsoncpp.a: error adding symbols: Bad value
```

Does that speak to you @bobsummerwill?

**Comment by bobsummerwill** [comment]
Yes it does, @anthony-cros!

Do you remember that we got something very similar before when flipping from ARMv5 to ARMv7 and then backing off again.

I think we would hit the same problem with a custom sample file for crosstool-NG as well.   We just haven't got to the bottom of the problem yet.

PIC is 'position independent code', which I assume translates into only using relative jumps throughout.  That is used so that apps can be loaded into.pseudo-random base addresses each time as a security feature.   For Android it became a required feature for Google Play at some point in the last few years

**Comment by bobsummerwill** [comment]
I assume that jsoncpp.a was not built with the PIC setting.   Is that an external binary?

**Comment by bobsummerwill** [comment]
No. Looks like we are building that.   So maybe easier to remove PIC throughout instead?   Just to get it working.

**Comment by anthony-cros** [comment]
Sounds good, it may not be easy though as it's used quite a lot!

> Do you remember that we got something very similar before when flipping from ARMv5 to ARMv7 and then backing off again.

Indeed, it was [this issue](https://github.com/doublethinkco/webthree-umbrella-cross/issues/10#issuecomment-160153195) (linking them)

**Comment by bobsummerwill** [comment]
Well we either need PIC everywhere or PIC nowhere :-)

**Comment by anthony-cros** [comment]
good news, I got libjsonrpccpp to go all the way, after adding -fPIC to jsoncpp :)

it's only a small hack

**Comment by anthony-cros** [comment]
getting this:

```
/usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/../../../../arm-linux-gnueabihf/bin/ld.gold: error: /home/xcompiler/eth/installs/cryptopp/lib/libcryptopp.a(basecode.o): requires unsupported dynamic reloc R_ARM_THM_MOVW_ABS_NC; recompile with -fPIC
```

when processing libweb3core, which confirms we'll need to make it a all-or-nothing (i'm more inclined to do the former) to get this working

**Comment by bobsummerwill** [comment]
Sure.    Please do keep hacking away at that, and commit whatever you can in your own branches for your required hacks.

**Comment by anthony-cros** [comment]
yes, the idea is basically to "augment" the CMakeList.txt file with something like `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")`

I still need to look into doing it for the autoconf and bare makefile dependencies (though presumably easier)

**Comment by anthony-cros** [comment]
successful run on ubuntu touch was:

```
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: SP and DP
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
```

**Comment by bobsummerwill** [comment]
They're all getting damn close now
ie. Sailfish ones, as reported by Martin:
sailfish libcurl
Attribute Section: aeabi
File Attributes
Tag_CPU_name: "7-A"
Tag_CPU_arch: v7
Tag_CPU_arch_profile: Application
Tag_ARM_ISA_use: Yes
Tag_THUMB_ISA_use: Thumb-2
Tag_FP_arch: VFPv3-D16
Tag_ABI_PCS_wchar_t: 4
Tag_ABI_FP_denormal: Needed
Tag_ABI_FP_exceptions: Needed
Tag_ABI_FP_number_model: IEEE 754
Tag_ABI_align_needed: 8-byte
Tag_ABI_align_preserved: 8-byte, except leaf SP
Tag_ABI_enum_size: int
Tag_ABI_HardFP_use: SP and DP
Tag_ABI_VFP_args: VFP registers
Tag_ABI_optimization_goals: Aggressive Speed
Tag_CPU_unaligned_access: v6
So maybe it
VFPv3 vs VFPv3-D16?
It's all down to tiny little differences now
Wikipedia says
VFPv3 or VFPv3-D32
Implemented on the Cortex-A8 and A9 ARMv7 processors. It is backwards compatible with VFPv2, except that it cannot trap floating-point exceptions. VFPv3 has 32 64-bit FPU registers as standard, adds VCVT instructions to convert between scalar, float and double, adds immediate mode to VMOV such that constants can be loaded into FPU registers.
VFPv3-D16
As above, but with only 16 64-bit FPU registers. Implemented on Cortex-R4 and R5 processors.

bobsummerwill 15:07
I believe Tizen is VFPv3-D16, just like Sailfish
Sounds like that is a subset of VFPv3, for shitter SOCs
So yeah, those binaries probably wouldn't "fly" on the TM1.
The only other difference is that apt compiler does:
Tag_ABI_FP_rounding: Needed
And Sailfish has:
Tag_ABI_align_preserved: 8-byte, except leaf SP
Tag_ABI_optimization_goals: Aggressive Speed
Table definitely needed, but yeah, getting a working Ubuntu Phone cross-build is great

bobsummerwill 15:12
From http://infocenter.arm.com/help/topic/com.arm.doc.ihi0045d/IHI0045D_ABI_addenda.pdf
2.3.7.1 Optimization attributes
The final pair of ABI-related tags record optimization goals. These are not required for reasoning about
incompatibility, but assist with selecting appropriate variants of library members.
Tag_ABI_optimization_goals, (=30), uleb128
0 No particular optimization goals, or no information recorded
1 Optimized for speed, but small size and good debug illusion preserved
2 Optimized aggressively for speed, small size and debug illusion sacrificed
3 Optimized for small size, but speed and debugging illusion preserved
4 Optimized aggressively for small size, speed and debug illusion sacrificed
5 Optimized for good debugging, but speed and small size preserved
6 Optimized for best debugging illusion, speed and small size sacrificed

**Comment by bobsummerwill** [comment]
So in conclusion, I think's likely all down to VFPv3 versus VFPv3-D16 now.
Looks like we're building a binary which assumes 32 FP registers, but there are only 16 on the TM1.
Boom!

**Comment by bobsummerwill** [comment]
Hey @phonikg and @martinbrook :-)
We've got a working cross-build for Ubuntu Phone (ARMv7) by using the GCC cross-compilers from the package repo, rather than our own.
When @anthony-cros shares binaries it would be great if you could see whether that gets C.H.I.P. to a happy place, @phonikg!
I think we're still broken for Sailfish and Tizen because they need VFPv3-D16 rather than VFPv3.

**Comment by bobsummerwill** [comment]
https://github.com/doublethinkco/webthree-umbrella-cross/releases/tag/crosseth-armhf-15-12-17

**Comment by anthony-cros** [comment]
alright, i can have a look at this VFPv3 versus VFPv3-D16, but I guess we'll have to make do with the ct-ng-based compilers to tweak these parameters :-S

**Comment by bobsummerwill** [comment]
@anthony-cros said ...

ok, just in case I get ran over by a truck before I can port this to the scripts, here are the hacks I had to do (very briefly):

    for jsoncpp, I added this at the end: set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
    for cryptopp, I uncommented the line CXXFLAGS += -fPIC in the GNUMakefile
    for libscrypt, I added this line: set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")

I'm just adding those notes here, because they are ARMv7 specific, and will be part of the work needed to get this issue to a conclusion.

Initially identified as needed for Sailfish, but really just ARMv7 / PIC related.

**Comment by bobsummerwill** [comment]
Note to self - armhf.sh build result this evening, which looks to be related to that hack removal ...

[ 76%] Building CXX object eth/CMakeFiles/eth.dir/main.cpp.o
cd /home/crosseth/eth/wd/webthree/eth && /home/crosseth/x-tools/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-g++   -DETH_FRONTIER -DETH_JSONRPC -DETH_TRUE -I/home/crosseth/eth/installs/libethereum/include -I/home/crosseth/eth/wd/libjson-rpc-cpp/src -I/home/crosseth/eth/installs/libjson-rpc-cpp/include/jsonrpccpp/common -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -Werror -pedantic -DSHAREDLIB -fPIC  -fuse-ld=gold -O0 -g -DETH_DEBUG -isystem /home/crosseth/eth/installs/jsoncpp/include/jsoncpp -I/home/crosseth/eth/wd/webthree-helpers/cmake/../../libethereum -isystem /home/crosseth/eth/wd/webthree-helpers/cmake/../utils -I/home/crosseth/eth/wd/webthree-helpers/cmake/../../libweb3core -I/home/crosseth/eth/wd/webthree-helpers/cmake/../../webthree -I/home/crosseth/eth/wd/webthree -I/home/crosseth/eth/wd/webthree/include -I/home/crosseth/eth/wd/webthree/gen -isystem /home/crosseth/eth/installs/libmicrohttpd/include -isystem /home/crosseth/eth/installs/leveldb/include -isystem /home/crosseth/eth/installs/boost/include -isystem /home/crosseth/eth/src -I/home/crosseth/eth/wd/webthree-helpers/cmake/../../libethereum/build/include -isystem /home/crosseth/eth/installs/libjson-rpc-cpp/include -isystem /home/crosseth/eth/installs/curl/include    -o CMakeFiles/eth.dir/main.cpp.o -c /home/crosseth/eth/wd/webthree/eth/main.cpp
/home/crosseth/eth/wd/webthree/eth/main.cpp: In function 'int main(int, char**)':
/home/crosseth/eth/wd/webthree/eth/main.cpp:885:3: error: 'JSRemoteConsole' was not declared in this scope
   JSRemoteConsole console(remoteURL);
   ^
/home/crosseth/eth/wd/webthree/eth/main.cpp:887:4: error: 'console' was not declared in this scope
    console.eval("web3.admin.setSessionKey('" + remoteSessionKey + "')");
    ^
/home/crosseth/eth/wd/webthree/eth/main.cpp:889:4: error: 'console' was not declared in this scope
    console.readAndEval();
    ^
make[2]: *** [eth/CMakeFiles/eth.dir/main.cpp.o] Error 1
make[2]: Leaving directory `/home/crosseth/eth/wd/webthree'
make[1]: *** [eth/CMakeFiles/eth.dir/all] Error 2
make[1]: Leaving directory `/home/crosseth/eth/wd/webthree'
make: *** [all] Error 2

**Comment by bobsummerwill** [comment]
OK - that was a hell of an effort.   Have ended up moving to Ubuntu Wily in the process, to get to a newer GCC.

https://github.com/doublethinkco/webthree-umbrella-cross/releases/tag/crosseth-armel-apt-2015-12-31
https://github.com/doublethinkco/webthree-umbrella-cross/releases/tag/crosseth-armhf-apt-2015-12-31

Updated the list of hacks at https://github.com/doublethinkco/webthree-umbrella-cross/issues/11
