### ISSUE TITLE
Cross-build V8

### ISSUE THREAD

**Issue by bobsummerwill** [doublethinkco/webthree-umbrella-cross#49]
How hard would it be to cross-build V8?    I think it is large, but it should be possible.

**Comment by anthony-cros** [comment]
it should be feasible, it's just that they use yet another build tool! so we'll need to get familiar with it first

**Comment by bobsummerwill** [comment]
What do they use?

**Comment by anthony-cros** [comment]
they use "gyp"

**Comment by bobsummerwill** [comment]
Hmm.

I wonder why the native build in Jenkins doesn't need to do a V8 build?

https://github.com/doublethinkco/eth-jenkins-config/blob/master/buildstep-config-files.xml

**Comment by bobsummerwill** [comment]
Doesn't look too dreadful:

    https://github.com/v8/v8/wiki/Building%20with%20Gyp

-----
Cross-compiling

Similar to building with Clang, you can also use a cross-compiler. Just export your toolchain (CXX/LINK environment variables should be enough) and compile. For example:

export CXX=/path/to/cross-compile-g++
export LINK=/path/to/cross-compile-g++
make arm.release
-----


Not a high priority right now, though.

**Comment by anthony-cros** [comment]
See [comment about flu](https://github.com/doublethinkco/webthree-umbrella-cross/issues/55#issuecomment-164107861)

**Comment by bobsummerwill** [comment]
Not going to bother with this.
Only required for the jsconsole, which will be removed.
