### ISSUE TITLE
Support incremental build process

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/webthree-umbrella-cross#5]

**Comment by bobsummerwill** [comment]
So that we have a working incremental build process, you mean?

**Comment by anthony-cros** [comment]
I mean that I'm not sure all components that are being built are actually useful to us, and considering how long the process takes, it may be worth looking into configuring that ct-ng build to remove unnecessary phases (if there are indeed any)

**Comment by bobsummerwill** [comment]
Right - so getting a better understanding of the COMPONENTS within eth, so that we can build a minimal executable?    And looking at the ct-ng build process.     There are some unconditional WGET calls within the eth build process too, I think, right?   Like Boost.

**Comment by anthony-cros** [comment]
yes, exactly, i'm sure we download and/or build a lot of bits that aren't needed at all. i just hope it's flexible enough to let you configure what you want specifically!
