### ISSUE TITLE
MHD is missing from our dependency graph, seemingly because it is an INDIRECT external dependency of libjson-rpc-cpp

### ISSUE THREAD

**Issue by bobsummerwill** [doublethinkco/webthree-umbrella-cross#54]

**Comment by anthony-cros** [comment]
Do you mean that the CMake file requires it but it isn't actually used in the code?

**Comment by bobsummerwill** [comment]
Well it doesn't even show up in the dependency graph, so looks like it has no CMake dependencies remaining.   Perhaps it was still used when you started work, and was eliminated as a dependency while you were working.

I see no remaining dependencies on it.

**Comment by anthony-cros** [comment]
I see, yes I remember getting errors without it at the time, but if it's no longer necessary, let's remove it for sure! I'll adapt the scripts

**Comment by anthony-cros** [comment]
https://github.com/doublethinkco/webthree-umbrella-cross/tree/mhd-removal

it's branched off my WIP branch though, as it contains a number of important changes

**Comment by anthony-cros** [comment]
actually I'm getting an error building libjson-rpc-cpp now:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MHD_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/xcompiler/eth/src/libjson-rpc-cpp/src/jsonrpccpp
   used as include directory in directory /home/xcompiler/eth/src/libjson-rpc-cpp/src/jsonrpccpp
   used as include directory in directory /home/xcompiler/eth/src/libjson-rpc-cpp/src/jsonrpccpp
MHD_LIBRARY (ADVANCED)
    linked by target "jsonrpcserver" in directory /home/xcompiler/eth/src/libjson-rpc-cpp/src/jsonrpccpp
```

**Comment by bobsummerwill** [comment]
So maybe we have only an indirect dependency on MHD via that external dependency?
That would make sense.
When I run the Dependency Graph generation, I am only iterating through the on-disk content in webthree-umbrella and its sub-modules.    Not into the external dependencies which we pull into our cross-build via WGET, etc.

I've updated the bug description.    This is now something which can be considered a bug in the dependency-graph generation script.    No need for you to spend more time on it, @anthony-cros.    Very low priority now.

**Comment by anthony-cros** [comment]
Sounds good, I'll nuke the corresponding branch! (it wasn't much work anyway)

**Comment by bobsummerwill** [comment]
Thanks!

**Comment by bobsummerwill** [comment]
See https://github.com/doublethinkco/webthree-umbrella-cross/blob/gh-pages/images/dependency_graph.svg.

Updated graph manually.
