### ISSUE TITLE
Cross-build flu when we can cross-build V8

### ISSUE THREAD

**Issue by bobsummerwill** [doublethinkco/webthree-umbrella-cross#55]
Why are we not cross-building flu?
Let's try to do that, rather than hacking it out of our cross-builds.

**Comment by anthony-cros** [comment]
Hey @bobsummerwill , the hacking out of flu wasn't in the original scripts, is it something you added later on because of an upstream change?

**Comment by bobsummerwill** [comment]
Yes.   I believe that I added the hack because it was a new module.

I tried enabling the flu build in a branch but it needs V8 so fails.   More hacks would be needed to chop out V8 to make it compile, but that's a bit pointless.

So for the time being, I think the answer is 'because with v8, flu is pointless'.

As-and-when we have v8 cross compiling, this can be revisited.

**Comment by bobsummerwill** [comment]
Flu is being deprecated, so this doesn't matter anymore.
