### ISSUE TITLE
CryptoPP to be removed

### ISSUE THREAD

**Issue by bobsummerwill** [doublethinkco/webthree-umbrella-cross#58]
bobsummerwill 16:10
Greetings! Anthony has delved back into the memory banks about the "package which was slated to be removed anyway" which both he and I had mis-remembered. The one we were thinking of was CryptoPP!
On Nov 5th, @anthony-cros said ...
Hi guys, I cross-compiled eth for ARM and tried running it on a tizen phone. I'm getting a seg fault about 2 seconds after starting the program (no logs). I went ahead and re-compiled with debug on, and here was the result (duplicate lines removed):
Starting program: /opt/usr/media/151103215114.3/bin/eth 
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
warning: the debug information found in "/usr/lib/debug/lib/libc-2.20-2014.11.so.debug" does not match "/lib/libc.so.6" (CRC mismatch).
warning: (Internal error: pc 0xb6c45424 in read in psymtab, but not in symtab.)
Program received signal SIGSEGV, Segmentation fault.
CryptoPP::BufferedTransformation::ChannelPut2(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char const*, unsigned int, int, bool) (warning: (Internal error: pc 0xb6c45424 in read in psymtab, but not in symtab.)

) at cryptlib.cpp:356
356    cryptlib.cpp: No such file or directory.
    in cryptlib.cpp
The sources for CryptoPP definitely contain a ./cryptlib.cpp and the logs of compilation don't seem to show anything unusual about this file: https://gist.github.com/anthony-cros/1540ff3393b0926ccce7
Any clues?
And @subtly replied ...
@bobsummerwill cryptopp generally isn't thread-safe; long-term a lot of changes should occur beginning with the removal of cryptopp (if its not already there)
So ... my dependency graph (https://github.com/doublethinkco/webthree-umbrella-cross/) tells me that CryptoPP has not been removed. Is there any Github issue tracking this TODO, @gavofyork? If not, I will log one, and we can put the confusion to bed. Thanks!
We haven't hit that specific seg fault on Tizen in the meantime since then, because of other ABI issues which we've been working through.

**Comment by anthony-cros** [comment]
this component in particular requires some very odd hacks on our side ([porting eth to other architectures](https://github.com/doublethinkco)):

1. [hack 1](https://github.com/doublethinkco/webthree-umbrella-cross/blob/master/cross-build/ethereum/cryptopp.sh#L22)
2. [hack 2](https://github.com/doublethinkco/webthree-umbrella-cross/blob/master/cross-build/ethereum/cryptopp.sh#L47)
3. [hack 3](https://github.com/doublethinkco/webthree-umbrella-cross/blob/master/cross-build/ethereum/utils.sh#L231)

**Comment by bobsummerwill** [comment]
Discussed on gitter.   This is a real TODO now.

See https://github.com/ethereum/webthree-umbrella/issues/103.
