### ISSUE TITLE
Sanity checks: parse log files

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/webthree-umbrella-cross#6]

**Comment by bobsummerwill** [comment]
Please could you explain this one more, @anthony-cros?   Thanks!

**Comment by anthony-cros** [comment]
So most steps output logs (or should), and I would add a quick check after each step to parse the logs and try and detect keywords we would expect to find, for instance "Using compiler /bla/bla/gnueabi/.../gcc" instead of using of just "Using compiler gcc"

it's happened often that a slight change in the environment would affect such a process, and it would crash further down the line and take me a while to figure out what the problem was

the idea is to catch the problem as early and as explicitely as possible
