### ISSUE TITLE
Please use Release instead of Debug version

### ISSUE THREAD

**Issue by CJentzsch** [doublethinkco/webthree-umbrella-cross#68]
I used the crosseth-armhf-apt-2015-12-31 (ARMv7) binary for my Raspberry Pi. It showed that the version is `++eth-v1.1.1-0/Debug-Linux/g++/int` - please use the Release version. EVMJIT instead of interpreter would also be nice.
Thanks!

**Comment by bobsummerwill** [comment]
Hey Christophe!
Thanks for the feedback :-)
Barring those details, you had a successful run, though?
I assume that was on a Pi2 Model B?

**Comment by bobsummerwill** [comment]
Could you try this one, please, @CJentzsch?

https://github.com/doublethinkco/webthree-umbrella-cross/releases/tag/crosseth-armhf-apt-2016-01-04

Same as before, except a Release build.   EVMJIT is proving a little more work :-)

**Comment by CJentzsch** [comment]
Thanks a lot, works like a charm!

**Comment by bobsummerwill** [comment]
Great!
See https://github.com/doublethinkco/webthree-umbrella-cross/issues/70.
EVMJIT looks like a LOT of work.   I will do it at some point, though.
