### ISSUE TITLE
Sanity checks for hacks

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/webthree-umbrella-cross#7]

**Comment by bobsummerwill** [comment]
Please could you explain this one more, @anthony-cros?   Thanks!

**Comment by anthony-cros** [comment]
in a similar way as with https://github.com/doublethinkco/webthree-umbrella-cross/issues/6#issuecomment-157902701, the idea is to ensure that each hacks have had the expected effect (it's easy to write an awk script with an unmet condition and that doesn't do its job)

some of the hacks already do that though, see https://github.com/doublethinkco/webthree-umbrella/blob/develop/cross-build/ethereum/boost.sh#L27 for instance

**Comment by bobsummerwill** [comment]
Right - thanks.
