### ISSUE TITLE
Use checksums/signatures for dependencies

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/webthree-umbrella-cross#8]

**Comment by bobsummerwill** [comment]
As in hard-code those within our scripts and double-check what we get given in the ZIPs?

**Comment by anthony-cros** [comment]
or ideally fetch it from the site we got the binaries from, as a number of them provided it

**Comment by bobsummerwill** [comment]
So probably want to add those checksums into our build process hardcoded, though, right?    To ensure that they don't change over time.   It is a "hardened" equivalent to plain versioning, which would be equivalent to sub-modules.     If we pull checksums and binaries at the same time, we don't gain any security, I don't think?

**Comment by anthony-cros** [comment]
true, and we can hardcode them along with the versions since the two are supposed to always evolve in sync

**Comment by bobsummerwill** [comment]
Right.
