### ISSUE TITLE
Add traps to scripts where appropriate

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/webthree-umbrella-cross#9]

**Comment by bobsummerwill** [comment]
Please could you explain this one more, @anthony-cros?   Thanks!

**Comment by anthony-cros** [comment]
the idea is to use [bash traps](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_12_02.html) for a cleaner error handling mechanism. maybe overkill for a shell script but well, it wouldn't hurt to have that in place!

**Comment by bobsummerwill** [comment]
What elements of the build process in particular do you think would benefit from trapping?

**Comment by anthony-cros** [comment]
basic things like my "grep" sanity checks for instance, trying to capture the failure (because the "-e" bash flag will make the program stop upon failure for grep to find a match) and displaying a more palatable error message

**Comment by bobsummerwill** [comment]
Gotcha.
